### PR TITLE
The preview interface is now fully scalable

### PR DESCRIPTION
**Pull request by tkolenbrander**
The interface does now scale to the screen size. Not much more to say here.

### CODE REVIEW

**Comment by bvobart** [comment]
The preview shots interface still doesn't scale properly as of yet. It seems the Shot settings menu on the side (which doesn't scale, but that is a good thing) has an invisible border that is just a bit too large for comfort.. The space between the actual camera image and the menu bar is also slightly too large as of now.

Also, though this may be more of a problem for @TimYuenior to fix, I still think this class is hideously verbose. There is also still commented code, an unused variable and if you enter something in 'Shot duration' that is not a number, then an uncaught exception is thrown. On the other hand, that is not something that concerns the feature this pull-request was made for.

**Comment by tkolenbrander** [comment]
@bvobart I fixed the space between the camera image and the menu bar, it is now the same as with the shot settings menu. The code is indeed hideous and I made a small adjustment to the way the imageviews are initialized, but this should mainly be Tims problem. I still have a question though, what do you exactly mean with the invisible border of the shot settings menu?

**Comment by bvobart** [comment]
@tkolenbrander That's right, should we make an issue out of it? And assign @TimYuenior ? Btw, I meant the 'hitbox' of the shot settings menu.

**Comment by tkolenbrander** [comment]
@bvobart I already changed the hitbox a bit in the previous commit, is it now fixed according to you?

**Comment by TimYuenior** [comment]
Will refactor the code. But for now, I think this branch can be merged, as scalability has been implemented.

**Comment by tkolenbrander** [comment]
Thank you for fixing the warning Bart. It is now ready to merge!

**Comment by bvobart** [comment]
It seems you have fixed the invisible border problem in commit 475b61f42123f1ac29e6ace441a709a89270f840. Nice!
I noticed that PMD gave an error in CameraLiveController, I fixed this for you. Other PMD, CheckStyle and FindBugs errors can be ignored for now or are not significant. I'll merge this branch once the build passes

**Pull request merged**
