### PR TITLE
Action field added.

### PR DESCRIPTION
**Pull request by Ettatabe**
Every shot now has an action field which can be used by a cameraman making his workflow easier.

### CODE REVIEW

**Comment by stevenmeijer** [comment]
Looks good, but maybe remove the "Changed here" in the javadoc again since it is no longer needed?

**Comment by Ettatabe** [comment]
@TH3steven this has been done :)

**Comment by tkolenbrander** [comment]
When I try to open the script creation menu I get the following error messages: [http://pastebin.com/qpxM1iHQ](http://pastebin.com/qpxM1iHQ)

Is this just my problem or is someone else having the same issues?

**Comment by stevenmeijer** [comment]
@tkolenbrander Fixed in 4a61bc2664bde65ed6eda05fb633469a40ccbac0, the FXML file still had some old naming in it that caused the nullpointer.

**Comment by tkolenbrander** [comment]
Thank you for the fix, it works great now! I have no remarks on the code, so according to me this pull-request is ready to merge.

**Comment by bvobart** [comment]
Looks and works good. I'll merge this now!

**Pull request merged**
