### PR TITLE
Presets are loaded automatically

### PR DESCRIPTION
**Pull request by tkolenbrander**
The loading of presets now automatically occurs when a camera is finished with its shot. Changes have been made in Script.java and Timeline.java. In order to test these new methods, new test cases have been added.

### CODE REVIEW

**Comment by stevenmeijer** [comment]
Travis seems to fail, look into that. The rest looks great tho!

**Comment by bvobart** [comment]
Your code looks good, nice job on adding tests for your methods as well! Travis seems to fail because of the following error while executing `mvn site`. This is weird, because you didn't mess around with the pom file or something.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project Context-TFP: failed to get report for org.apache.maven.plugins:maven-pmd-plugin: Plugin org.apache.maven.plugins:maven-pmd-plugin:3.6 or one of its dependencies could not be resolved: Could not transfer artifact net.sourceforge.pmd:pmd-core:jar:5.3.5 from/to central (https://repo.maven.apache.org/maven2): GET request of: net/sourceforge/pmd/pmd-core/5.3.5/pmd-core-5.3.5.jar from central failed: Connection reset -> [Help 1]`

**Comment by bvobart** [comment]
@TH3steven The build passed by simply restarting the build. I assume you noticed this and that's why you merged it? Please comment on that next time, as currently it looks as if this PR was merged while Travis was not passing.

**Comment by stevenmeijer** [comment]
@bvobart Yes, since the only thing keeping this branch from being merged was Travis failing for no reason, I merged it since it now does not fail any more.

**Pull request merged**
