### PR TITLE
Added observable counter

### PR DESCRIPTION
**Pull request by tkolenbrander**
The counter in the database is now observable by anyone. This is useful in order to update the GUI.

### CODE REVIEW

**Comment by tkolenbrander** [comment]
Pull request 100, nice!

**Comment by tkolenbrander** [comment]
Thank you for fixing the tests Bart, time to do some code review!

**Comment by bvobart** [comment]
This looks good, nothing to comment on here. I think this can be merged.

**Comment by Ettatabe** [comment]
I agree with @bvobart. The code looks quite okay so I say merge

**Comment by stevenmeijer** [comment]
Looks good, merging

**Pull request merged**
