### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by stevenmeijer**
Pull all changes for sprint 8 into the master to prepare for release. All changes have been reviewed in the different PRs

### CODE REVIEW

**Comment by stevenmeijer** [comment]
Looks good, this is ready for release once Travis finishes. Great work u guys

**Comment by Ettatabe** [comment]
Yes.. I agree
Has been a hectic week and a tough friday especially but we are almost there. Good job guys :) @TH3steven @tkolenbrander @bvobart @TimYuenior

**Comment by bvobart** [comment]
Yes, this can be merged once the build passes. Today we've probably set the record for the most hours worked on the project on a single day so far. I'll merge this now.

**Comment by bvobart** [comment]
Thanks for notifying me on WhatsApp before merging and fixing those last CheckStyle errors, Steven. Once the build passes again, then we'll merge.

**Pull request merged**
