### PR TITLE
Script saving

### PR DESCRIPTION
**Pull request by stevenmeijer**
Implement the backend script saving in the front end and allow for editing and loading of a script.

### CODE REVIEW

**Comment by tkolenbrander** [comment]
Code looks good, I can't find anything to put feedback on.

**Comment by bvobart** [comment]
Same as Thomas here, your code looks good!

**Comment by Ettatabe** [comment]
I think your code is ready for merging. I don't find anything wrong in it. Perfect job buddy.

**Comment by TimYuenior** [comment]
Everything seems fine here. Merging!

**Pull request merged**
