### PR TITLE
Package fix

### PR DESCRIPTION
**Pull request by TimYuenior**
Packages structure is now fixed.

### CODE REVIEW

**Comment by bvobart** [comment]
The Travis build does not pass. What is going wrong here?

**Comment by Ettatabe** [comment]
I think the build fails because some test files also failed from what I can notice on travis. This should have something to do with the changed package names.

**Comment by tkolenbrander** [comment]
Travis passes now, time to merge!

**Comment by stevenmeijer** [comment]
Looks good to me

**Comment by bvobart** [comment]
Yes, looks good now!

**Pull request merged**
