### PR TITLE
Camera control using arrow keys

### PR DESCRIPTION
**Pull request by bvobart**
In the Edit Presets menu, there is now a checkbox, which when ticked allows the user to control the camera using the arrow keys. Two new methods have been made for this in the CameraConnection class.

### CODE REVIEW

**Comment by tkolenbrander** [comment]
When there is no camera selected, I get a nullpointer. Please fix this.

**Comment by tkolenbrander** [comment]
Code looks good. Please fix the merge conflicts and we are ready to merge!

**Comment by Ettatabe** [comment]
I agree with @tkolenbrander . Nice fix on the snapshotTest in MockedCameraConnectTest class :) @bvobart

**Comment by tkolenbrander** [comment]
The arrow control works right? Since that is the main purpose of this PR we could merge this and fix the bugs in the fixez branch.

**Comment by Ettatabe** [comment]
branch still has conflicts that have to be resolved. Once that is done, I will merge this PR

**Comment by Ettatabe** [comment]
Looks good. Conflicts have been fixed and as such, I will then merge this

**Pull request merged**
