### PR TITLE
Adds SIG configuration file

### PR DESCRIPTION
**Pull request by stevenmeijer**
Adds a configuration file for SIG. Push into master since SIG appears to check the master.

### CODE REVIEW

**Comment by bvobart** [comment]
I'm not sure if the component depth should indeed be 7, because our classes start in src/main/java/nl/tudelft/contextproject/ or if it should be 4, because our packages start in src/main/java/. I'm leaning towards 7 and since I cannot load [the scope manual](https://bettercodehub.sig.eu/#/docs/scope-manual), we'll see what the SIG tool makes of it... Let's merge this.

**Comment by Ettatabe** [comment]
I am with @bvobart. Curious about what SIG tools make of the depth as well but I think 7 sounds more logical to me. I will merge this anyways

**Comment by stevenmeijer** [comment]
SIG appears to work fine with these setting btw. (At least, the part of SIG that works in the first place)

**Comment by bvobart** [comment]
@TH3steven As far as SIG's software works, that is :laughing:

**Pull request merged**
