### PR TITLE
Reset script

### PR DESCRIPTION
**Pull request by TimYuenior**
a reset script button is added to the director live UI. I did not know where to place it, so its position is subject to change.
This branch also fixes the initial shot selection in the director view, the preset field in the table and the preset values in the choicebox. The fix to the initial shot selection in the table uses Platform.runLater().
I also merged the fixez branch into here already, so you can try it out the application on this branch. It only misses the implementation of Thomas's synchronisation branch.

### CODE REVIEW

**Comment by TimYuenior** [comment]
This branch has also deleted the preview script UI now.

**Comment by tkolenbrander** [comment]
Please also reset the database counter when the rest button is pressed. You can do this with "DatabaseConnection.getInstance().resetCounter()"

**Comment by stevenmeijer** [comment]
After resolving the merge conflicts, you get my seal of approval

**Comment by tkolenbrander** [comment]
Travis passes, let's merge!

**Pull request merged**
